name: flutter_energy
description: IoT Energy Management System
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  logger: ^2.5.0
  shared_preferences: ^2.5.2
  flutter_animate: ^4.5.2
  intl: ^0.19.0
  flutter_native_splash: ^2.4.4
  flutter_svg: ^2.0.16
  connectivity_plus: ^6.1.1
  awesome_dialog: ^3.2.1
  pinput: ^5.0.0
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  lottie: ^3.3.1
  fl_chart: ^0.70.2
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  timeago: ^3.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2



flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg_icons/
    - assets/fonts/

  fonts:
    - family: DINRound
      fonts:
        - asset: assets/fonts/din-round-bold.ttf
          weight: 700
        - asset: assets/fonts/din-round-light.ttf
          weight: 300
